spring.application.name=taskmanagementsystem

spring.datasource.url=jdbc:mysql://localhost:3306/task_management_system
spring.datasource.username=root
spring.datasource.password=$aini#6002@1072

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# spring.security.user.name=admin
# spring.security.user.password=admin123